In [1]:
import os
import time
import uuid
import cv2
import tensorflow as tf
import json
import numpy as np
import matplotlib.pyplot as plt

In [2]:
IMAGES_PATH = os.path.join('data', 'images')
NUM_IMAGES = 30

In [4]:
cap = cv2.VideoCapture(0)

while cap.isOpened():
    
#for num_image in range(NUM_IMAGES):
    #print('collecting image {}'.format(num_image))
    
    ret, frame = cap.read()
    
    #imgname = os.path.join(IMAGES_PATH, f'{str(uuid.uuid1())}.jpg')
    
    #cv2.imwrite(imgname, frame)
    
    cv2.imshow('collecting the images', frame)
    
    #time.sleep(0.5)
    
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [ ]:
!labelme

In [ ]:
#setting the gpu growth

gpus = tf.config.experimental.list_physical_devices('GPU')

for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

In [ ]:
tf.config.experimental.list_physical_devices('GPU')

In [ ]:
images = tf.data.Dataset.list_files('data\\images\\*jpg')

In [ ]:
images.as_numpy_iterator().next()

In [ ]:
#to load an image from byte to jpg

def load_img(x):
    byte_image = tf.io.read_file(x)
    img = tf.io.decode_jpeg(byte_image)
    
    return img

In [ ]:
images = images.map(load_img)

In [ ]:
image_generator = images.batch(4).as_numpy_iterator()

In [ ]:
plot_images = image_generator.next()

In [ ]:
fig, ax = plt.subplots(ncols = 4, figsize = (10, 10))

for idx, image in enumerate(plot_images):
    ax[idx].imshow(image)
    
plt.show()

In [ ]:
#moving the matching labels to the corresponding folders of test, train and val

for folder in ['train', 'test', 'val']:
    for file in os.listdir(os.path.join('data', folder, 'images')):
        
        filename = file.split(".")[0] + '.json'
        
        existing_filepath = os.path.join('data', 'labels', filename)
        
        if os.path.exists(existing_filepath):
            new_filepath = os.path.join('data', folder, 'labels', filename)
            os.replace(existing_filepath, new_filepath)

In [ ]:
augmentor = alb.Compose([alb.RandomCrop(width=450, height=450), 
                         alb.HorizontalFlip(p=0.5), 
                         alb.RandomBrightnessContrast(p=0.2),
                         alb.RandomGamma(p=0.2), 
                         alb.RGBShift(p=0.2), 
                         alb.VerticalFlip(p=0.5)], 
                       bbox_params=alb.BboxParams(format='albumentations', 
                                                  label_fields=['class_labels']))

In [12]:
#loading an image and annotation from the test set

In [13]:
img = cv2.imread(os.path.join('data', 'test', 'images', '8a8f6be4-17e1-11ee-994e-00e04c33d143.jpg'))

In [14]:
with open(os.path.join('data', 'test', 'labels', '8a8f6be4-17e1-11ee-994e-00e04c33d143.json'), 'r') as f:
    label = json.load(f)

In [15]:
label

{'version': '5.2.1',
 'flags': {},
 'shapes': [{'label': 'face',
   'points': [[224.74452554744528, 91.82481751824818],
    [430.5839416058394, 353.86861313868616]],
   'group_id': None,
   'description': '',
   'shape_type': 'rectangle',
   'flags': {}}],
 'imagePath': '..\\images\\8a8f6be4-17e1-11ee-994e-00e04c33d143.jpg',
 'imageData': '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAHgAoADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGR

In [18]:
label['shapes']

[{'label': 'face',
  'points': [[224.74452554744528, 91.82481751824818],
   [430.5839416058394, 353.86861313868616]],
  'group_id': None,
  'description': '',
  'shape_type': 'rectangle',
  'flags': {}}]

In [19]:
label['shapes'][0]

{'label': 'face',
 'points': [[224.74452554744528, 91.82481751824818],
  [430.5839416058394, 353.86861313868616]],
 'group_id': None,
 'description': '',
 'shape_type': 'rectangle',
 'flags': {}}

In [20]:
label['shapes'][0]['points']

[[224.74452554744528, 91.82481751824818],
 [430.5839416058394, 353.86861313868616]]

In [21]:
#rescaling the coordinates to the image resolution

In [22]:
coords = [0, 0, 0, 0]
coords[0] = label['shapes'][0]['points'][0][0]
coords[1] = label['shapes'][0]['points'][0][1]
coords[2] = label['shapes'][0]['points'][1][0]
coords[3] = label['shapes'][0]['points'][1][1]

In [23]:
coords = list(np.divide(coords, [640, 480, 640, 480]))

In [24]:
coords

[0.35116332116788324,
 0.19130170316301703,
 0.6727874087591241,
 0.7372262773722629]

In [25]:
#now applying augmetnations to our image and labels or coords

In [27]:
augmented_image = augmenter(image = img, bboxes = [coords], class_labels = ['face'])

In [28]:
augmented_image

{'image': array([[[186, 190, 179],
         [186, 190, 179],
         [186, 190, 179],
         ...,
         [183, 186, 177],
         [183, 186, 177],
         [182, 185, 176]],
 
        [[186, 190, 179],
         [186, 190, 179],
         [186, 190, 179],
         ...,
         [184, 187, 178],
         [183, 186, 177],
         [182, 185, 176]],
 
        [[188, 192, 181],
         [187, 191, 180],
         [185, 190, 181],
         ...,
         [186, 189, 180],
         [185, 188, 179],
         [184, 187, 178]],
 
        ...,
 
        [[225, 216, 173],
         [225, 216, 173],
         [227, 215, 173],
         ...,
         [240, 237, 206],
         [240, 236, 207],
         [240, 236, 207]],
 
        [[223, 215, 175],
         [223, 216, 173],
         [225, 216, 173],
         ...,
         [239, 236, 205],
         [239, 236, 205],
         [239, 236, 205]],
 
        [[223, 215, 175],
         [223, 215, 175],
         [224, 215, 172],
         ...,
         [239, 236,

In [30]:
augmented_image['bboxes'][0][2:]

(0.6635198702351986, 0.7819302514193026)

In [ ]:
cv2.rectangle(augmented_image['image'],
              tuple(np.multiply(augmented_image['bboxes'][0][:2], [450, 450]).astype(int)),
              tuple(np.multiply(augmented_image['bboxes'][0][2:], [450, 450]).astype(int)),
              (0, 0, 255), 2)

plt.imshow(augmented_image['image'])

In [33]:
#now making an augmentation pipeline

In [92]:
for partition in ['train','test','val']:
    for image in os.listdir(os.path.join('data', partition, 'images')):
        img = cv2.imread(os.path.join('data', partition, 'images', image))

        coords = [0,0,0.00001,0.00001]
        label_path = os.path.join('data', partition, 'labels', f'{image.split(".")[0]}.json')
        if os.path.exists(label_path):
            with open(label_path, 'r') as f:
                label = json.load(f)

            coords[0] = label['shapes'][0]['points'][0][0]
            coords[1] = label['shapes'][0]['points'][0][1]
            coords[2] = label['shapes'][0]['points'][1][0]
            coords[3] = label['shapes'][0]['points'][1][1]
            coords = list(np.divide(coords, [640,480,640,480]))

        try:
            for x in range(60):
                augmented = augmentor(image=img, bboxes=[coords], class_labels=['face'])
                cv2.imwrite(os.path.join('DATA', partition, 'images', f'{image.split(".")[0]}.{x}.jpg'), augmented['image'])

                annotation = {}
                annotation['image'] = image

                if os.path.exists(label_path):
                    if len(augmented['bboxes']) == 0:
                        annotation['bbox'] = [0,0,0,0]
                        annotation['class'] = 0
                    else:
                        annotation['bbox'] = augmented['bboxes'][0]
                        annotation['class'] = 1
                else:
                    annotation['bbox'] = [0,0,0,0]
                    annotation['class'] = 0


                with open(os.path.join('DATA', partition, 'labels', f'{image.split(".")[0]}.{x}.json'), 'w') as f:
                    json.dump(annotation, f)

        except Exception as e:
            print(e)

In [38]:
#loading the augmented dataset in our tensorflow dataset pipeline

In [93]:
def load_image(x):
    byte_img = tf.io.read_file(x)
    img = tf.io.decode_jpeg(byte_img)
    return img

In [95]:
train_images = tf.data.Dataset.list_files('DATA/train/images/*.jpg', shuffle=False)
train_images = train_images.map(load_image)
train_images = train_images.map(lambda x: tf.image.resize(x, (120,120)))
train_images = train_images.map(lambda x: x/255)

In [96]:
test_images = tf.data.Dataset.list_files('DATA/test/images/*.jpg', shuffle=False)
test_images = test_images.map(load_image)
test_images = test_images.map(lambda x: tf.image.resize(x, (120,120)))
test_images = test_images.map(lambda x: x/255)

In [97]:
val_images = tf.data.Dataset.list_files('DATA/val/images/*.jpg', shuffle=False)
val_images = val_images.map(load_image)
val_images = val_images.map(lambda x: tf.image.resize(x, (120,120)))
val_images = val_images.map(lambda x: x/255)

In [98]:
train_images.as_numpy_iterator().next()

array([[[0.66795343, 0.84932595, 0.8713848 ],
        [0.7275735 , 0.8865809 , 0.9026961 ],
        [0.7372549 , 0.88235295, 0.9107843 ],
        ...,
        [0.6021446 , 0.7746936 , 0.7864583 ],
        [0.5980392 , 0.75030637, 0.7670343 ],
        [0.5984681 , 0.7332721 , 0.7405025 ]],

       [[0.5659314 , 0.7362132 , 0.78278184],
        [0.7400122 , 0.8958946 , 0.9042279 ],
        [0.75692403, 0.8941789 , 0.9088848 ],
        ...,
        [0.6186887 , 0.77947307, 0.79515934],
        [0.6082721 , 0.74699754, 0.75533086],
        [0.61697304, 0.73835784, 0.7490196 ]],

       [[0.27144608, 0.43860295, 0.503799  ],
        [0.7047181 , 0.86360294, 0.8860907 ],
        [0.75147057, 0.9004902 , 0.9122549 ],
        ...,
        [0.61960787, 0.7808211 , 0.7873775 ],
        [0.61476713, 0.77248776, 0.76862746],
        [0.62107843, 0.752451  , 0.75      ]],

       ...,

       [[0.7463848 , 0.78707105, 0.7787377 ],
        [0.76121324, 0.8043505 , 0.78682595],
        [0.7681373 , 0

In [99]:
def load_labels(label_path):
    with open(label_path.numpy(), 'r', encoding = "utf-8") as f:
        label = json.load(f)

    return [label['class']], label['bbox']

In [100]:
train_labels = tf.data.Dataset.list_files('DATA/train/labels/*.json', shuffle=False)
train_labels = train_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [101]:
test_labels = tf.data.Dataset.list_files('DATA/test/labels/*.json', shuffle=False)
test_labels = test_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [102]:
val_labels = tf.data.Dataset.list_files('DATA/val/labels/*.json', shuffle=False)
val_labels = val_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [103]:
len(train_images), len(train_labels), len(test_images), len(test_labels), len(val_images), len(val_labels)


(1080, 1080, 360, 360, 300, 300)

In [82]:
#combining the labels and the image together

In [104]:
train = tf.data.Dataset.zip((train_images, train_labels))
train = train.shuffle(5000)
train = train.batch(8)
train = train.prefetch(4)

In [105]:
test = tf.data.Dataset.zip((test_images, test_labels))
test = test.shuffle(1300)
test = test.batch(8)
test = test.prefetch(4)

In [106]:
val = tf.data.Dataset.zip((val_images, val_labels))
val = val.shuffle(1000)
val = val.batch(8)
val = val.prefetch(4)

In [107]:
train.as_numpy_iterator().next()[1]

(array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]], dtype=uint8),
 array([[0.24   , 0.1364 , 0.6685 , 0.678  ],
        [0.0573 , 0.1781 , 0.5083 , 0.8643 ],
        [0.2048 , 0.1774 , 0.643  , 0.758  ],
        [0.102  , 0.2568 , 0.574  , 0.9155 ],
        [0.08307, 0.04617, 0.5776 , 0.752  ],
        [0.224  , 0.118  , 0.675  , 0.804  ],
        [0.223  , 0.266  , 0.718  , 0.9717 ],
        [0.4993 , 0.06433, 0.9697 , 0.7036 ]], dtype=float16))

In [109]:
#making the deep learning model

In [110]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, Dense, GlobalMaxPooling2D
from tensorflow.keras.applications import VGG16

In [112]:
vgg = VGG16(include_top = False)

58889256/58889256 [==============================] - 0s 0us/step


In [113]:
def build_model():
  input_layer = Input(shape = (120, 120, 3))

  vgg = VGG16(include_top = False)(input_layer)

  #classification model
  f1 = GlobalMaxPooling2D()(vgg)
  class1 = Dense(2048, activation = 'relu')(f1)
  class2 = Dense(1, activation = 'sigmoid')(class1)

  #regression loss
  f1 = GlobalMaxPooling2D()(vgg)
  regres1 = Dense(2048, activation = 'relu')(f1)
  regres2 = Dense(4, activation = 'sigmoid')(regres1)

  facetracker = Model(inputs = input_layer, outputs = [class2, regres2])

  return facetracker

In [114]:
facetracker = build_model()

In [115]:
facetracker.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_2 (InputLayer)           [(None, 120, 120, 3  0           []                               
                                )]                                                                
                                                                                                  
 vgg16 (Functional)             (None, None, None,   14714688    ['input_2[0][0]']                
                                512)                                                              
                                                                                                  
 global_max_pooling2d (GlobalMa  (None, 512)         0           ['vgg16[0][0]']                  
 xPooling2D)                                                                                  

In [116]:
X, y = train.as_numpy_iterator().next()

In [117]:
X.shape

(8, 120, 120, 3)

In [118]:
classes, coords = facetracker.predict(X)

1/1 [==============================] - 10s 10s/step


In [119]:
classes

array([[0.5893438 ],
       [0.74408567],
       [0.51121366],
       [0.551796  ],
       [0.5994262 ],
       [0.63766974],
       [0.5690109 ],
       [0.46554455]], dtype=float32)

In [120]:
coords

array([[0.33478627, 0.40122658, 0.37259132, 0.37758005],
       [0.3946936 , 0.38691047, 0.3823151 , 0.36963627],
       [0.35267124, 0.29128823, 0.33727336, 0.41001254],
       [0.38308996, 0.38366228, 0.32710922, 0.44137123],
       [0.35661465, 0.3958627 , 0.41427523, 0.363432  ],
       [0.33384854, 0.3226989 , 0.38137263, 0.3608766 ],
       [0.4198646 , 0.31612223, 0.34842077, 0.4269532 ],
       [0.39756805, 0.36370334, 0.32280356, 0.44559598]], dtype=float32)

In [121]:
batches_per_epoch = len(train)
lr_decay = (1/0.75 - 1)/batches_per_epoch

In [123]:
opt = tf.keras.optimizers.Adam(learning_rate = 0.0001)

In [124]:
#defining the regression loss

In [125]:
def localization_loss(y_true, ypred):
  delta_coord = tf.reduce_sum(tf.square(y_true[:, :2] - ypred[:, :2]))

  h_true = y_true[:, 3] - y_true[:, 1]
  w_true = y_true[:, 2] - y_true[:, 0]

  h_pred = ypred[:, 3] - ypred[:, 1]
  w_pred = ypred[:, 2] - ypred[:, 0]

  delta_size = tf.reduce_sum(tf.square(w_true - w_pred) + tf.square(h_true - h_pred))

  return delta_coord + delta_size

In [126]:
classloss = tf.keras.losses.BinaryCrossentropy()
regressloss = localization_loss

In [130]:
localization_loss(y[1], coords)

<tf.Tensor: shape=(), dtype=float32, numpy=4.5345855>

In [131]:
classloss(y[0], classes)

<tf.Tensor: shape=(), dtype=float32, numpy=0.54750097>

In [132]:
#training a neural network

In [135]:
class Facetracker(Model):

  def __init__(self, facetracker, **kwargs):
    super().__init__(**kwargs)
    self.model = facetracker


  def compile(self, opt, classloss, regressloss, **kwargs):
    super().compile(**kwargs)
    self.opt = opt
    self.classloss = classloss
    self.regressloss = regressloss

  def train_step(self, batch, **kwargs):
    X, y = batch

    with tf.GradientTape() as tape:
      classes, coords = self.model(X, training = True)

      batch_classloss = self.classloss(y[0], classes)
      batch_localization_loss = self.regressloss(tf.cast(y[1], tf.float32), coords)

      total_loss = batch_localization_loss + 0.5*batch_classloss

      grad = tape.gradient(total_loss, self.model.trainable_variables)

    opt.apply_gradients(zip(grad, self.model.trainable_variables))

    return {"total_loss":total_loss, "class_loss":batch_classloss, "regress_loss":batch_localization_loss}

  def test_step(self, batch, **kwargs):
    X, y = batch

    classes, coords = self.model(X, training = False)

    batch_classloss = self.classloss(y[0], classes)
    batch_localization_loss = self.regressloss(tf.cast(y[1], tf.float32), coords)

    total_loss = batch_localization_loss + 0.5*batch_classloss

    return {"total_loss":total_loss, "class_loss":batch_classloss, "regress_loss":batch_localization_loss}


  def call(self, X, **kwargs):
    return self.model(X, **kwargs)


In [136]:
model = Facetracker(facetracker)

In [137]:
model.compile(opt, classloss, regressloss)

In [138]:
logdir='logs'
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)

In [139]:
hist = model.fit(train, epochs = 100, validation_data = val, callbacks = [tensorboard_callback])

Epoch 1/100
135/135 [==============================] - 24s 77ms/step - total_loss: 0.1837 - class_loss: 0.0095 - regress_loss: 0.1790 - val_total_loss: 0.0145 - val_class_loss: 2.8700e-05 - val_regress_loss: 0.0145
Epoch 2/100
135/135 [==============================] - 11s 66ms/step - total_loss: 0.0248 - class_loss: 6.0237e-05 - regress_loss: 0.0248 - val_total_loss: 0.0207 - val_class_loss: 1.3024e-05 - val_regress_loss: 0.0207
Epoch 3/100
135/135 [==============================] - 11s 66ms/step - total_loss: 0.0196 - class_loss: 1.9657e-05 - regress_loss: 0.0196 - val_total_loss: 0.0214 - val_class_loss: 5.6327e-06 - val_regress_loss: 0.0214
Epoch 4/100
135/135 [==============================] - 12s 68ms/step - total_loss: 0.0139 - class_loss: 7.7859e-06 - regress_loss: 0.0139 - val_total_loss: 0.0113 - val_class_loss: 3.0994e-06 - val_regress_loss: 0.0113
Epoch 5/100
135/135 [==============================] - 12s 71ms/step - total_loss: 0.0097 - class_loss: 3.7949e-06 - regress_los

In [140]:
test_data = test.as_numpy_iterator()

In [144]:
test_sample = test_data.next()

In [145]:
yhat = facetracker.predict(test_sample[0])

1/1 [==============================] - 0s 20ms/step


In [ ]:
fig, ax = plt.subplots(ncols = 4, figsize = (20, 20))

for idx in range(4):

  sample_image = test_sample[0][idx]
  sample_coords = yhat[1][idx]

  if yhat[0][idx] > 0.9:
    cv2.rectangle(sample_image,
                  tuple(np.multiply(sample_coords[:2], [120, 120]).astype(int)),
                  tuple(np.multiply(sample_coords[2:], [120, 120]).astype(int)),
                  (0, 0, 255), 2)

  ax[idx].imshow(sample_image)

In [147]:
facetracker.save('facedetection.h5')

In [9]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import cv2
import numpy as np

In [4]:
facetracker = load_model('facedetection.h5')

In [10]:
cap = cv2.VideoCapture(0)
while cap.isOpened():
    _ , frame = cap.read()
    frame = frame[50:500, 50:500,:]
    
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    resized = tf.image.resize(rgb, (120,120))
    
    yhat = facetracker.predict(np.expand_dims(resized/255,0))
    sample_coords = yhat[1][0]
    
    if yhat[0] > 0.5: 
        # Controls the main rectangle
        cv2.rectangle(frame, 
                      tuple(np.multiply(sample_coords[:2], [450,450]).astype(int)),
                      tuple(np.multiply(sample_coords[2:], [450,450]).astype(int)), 
                            (255,0,0), 2)
        # Controls the label rectangle
        cv2.rectangle(frame, 
                      tuple(np.add(np.multiply(sample_coords[:2], [450,450]).astype(int), 
                                    [0,-30])),
                      tuple(np.add(np.multiply(sample_coords[:2], [450,450]).astype(int),
                                    [80,0])), 
                            (255,0,0), -1)
        
        # Controls the text rendered
        cv2.putText(frame, 'face', tuple(np.add(np.multiply(sample_coords[:2], [450,450]).astype(int),
                                               [0,-5])),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
    
    cv2.imshow('EyeTrack', frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [12]:
model = load_model('facedetection.h5')